services:
 app:
  build:
   context: .
   dockerfile: docker-services/app/Dockerfile
  restart: on-failure:5
  container_name: customer-management-api-app
  env_file:
   - .env
  depends_on:
   - db
  volumes:
   - ./src:/app/src
   - ./logs:/app/logs
   - ./prisma:/app/prisma
   - ./generated:/app/generated
   - .env:/app/.env

 server:
  image: nginx:latest
  restart: on-failure:5
  container_name: customer-management-api-server
  volumes:
   - ./docker-services/server/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - '85:80'
  depends_on:
   - app

 db:
  image: postgres
  restart: on-failure:5
  environment:
   - POSTGRES_DB=${POSTGRES_DB}
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  container_name: customer-management-api-db
  volumes:
   - ./docker-services/db/pgdata:/var/lib/postgresql/data
  ports:
   - '5432:5432'

 pgadmin:
  image: dpage/pgadmin4
  container_name: customer-management-api-pgadmin
  environment:
   - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
   - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  ports:
   - '5050:80'
  depends_on:
   - db
