services:
 - type: web
   name: customer-management-api-app
   plan: free
   region: frankfurt
   runtime: docker
   dockerfilePath: ./docker-services/app/Dockerfile
   repo: https://github.com/alexanderbrv/customer-management-api
   autoDeployTrigger: commit
   dockerCommand: npm run start:prod
   envVarGroups:
    - name: customer-management-api-env-group
      envVars:
       - key: DATABASE_URL
         fromDatabase:
          name: customer-management-api-db
          property: connectionString

databases:
 - name: customer-management-api-db
   databaseName: customer_management_api
   plan: free
   region: frankfurt
